SEG/urls.py
from django.contrib import admin
from django.urls import path, include
#from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView as rv

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',include('login.urls')),
    path('home/', include('home.urls')),
    path('report/',include('reports.urls')),
    path('', rv.as_view(url='/login/', permanent=False)),
]

#Serving static files during development
"""if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    """

home/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', contract, name = 'contract'),
    path('form/', welcome, name='form'),
    path('logout/', clogout, name='logout'),
    path('import_contractors/', import_contractors, name ='import_contractors'),
    path('handle_contractors/', handle_contractors, name = 'handle_contractors'),
    path('review_contractors/', review_contractors, name = 'review_contractors')
]

home/models.py
from django.db import models
from django.core.exceptions import ValidationError
# Create your models here.
class Contractor(models.Model):
    
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    phone = models.CharField(max_length=15)
    email = models.TextField()
    badge = models.CharField(max_length=20)
    created_by = models.CharField(max_length=20)
    created_on = models.DateTimeField()
    id = models.IntegerField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'contractors'

class Communications(models.Model):
    COMM_CLASS = ((0,'Batch'), 
                  (1, 'One to One'))
    
    SERVICE_TYPE = ((0,'Chat'), 
                    (1,'Call'))
    
    COMM_TYPE = ((0, 'Inbound'),
                 (1,'Outbound'))
    
    #contractor = models.ForeignKey('Contractors', on_delete=models.CASCADE)
    comm_class = models.IntegerField(choices=COMM_CLASS)
    label = models.TextField()
    service_type = models.IntegerField(choices=SERVICE_TYPE)
    comm_type = models.IntegerField(choices = COMM_TYPE)
    message = models.TextField()
    created_by = models.CharField(max_length=20)
    created_on = models.DateField(auto_now_add = False)
    notes = models.TextField()
    is_parent = models.BooleanField(default = False)
    parent_id = models.IntegerField(default = 0)

    def __str__(self):
        return self.label
    
    """ def parent_id_def(self, *args, **kwargs):
        if not self.is_parent:
            self.parent_id = 0
        super().save(*args, **kwargs)"""
    


class todo(models.Model):

    STATUS = ((0,'Pending'),
              (1, 'Completed'))

    task = models.TextField()
    status = models.IntegerField(choices = STATUS)
    description = models.TextField()
    assigned_to = models.CharField(max_length = 30)
    created_by = models.CharField(max_length = 30)
    added_on = models.DateField(auto_now_add = False)
    comm_id = models.IntegerField()

    def clean(self):
        try:
            comm = Communications.objects.get(id=self.comm_id)
        except Communications.DoesNotExist:
            raise ValidationError("Communication with this ID does not exist")

home/forms.py
from django import forms
from .models import Communications, todo

class CommunicatonsForm(forms.ModelForm):
    class Meta:
        model = Communications
        fields  = '__all__'
        widgets = {
            'created_on': forms.DateInput(attrs={'type': 'date'}),
        }
        

class TodoForm(forms.ModelForm):
    class Meta:
        model = todo
        fields = '__all__'
        widgets = {
            'added_on': forms.DateInput(attrs={'type': 'date'}),
        }


class UploadFileForm(forms.Form):
    file = forms.FileField()

class SelectContractors(forms.Form):
    contractor = forms.MultipleChoiceField(widget = forms.CheckboxSelectMultiple)          

home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.db import connection
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib import messages
from django.urls import reverse
from django.views.decorators.cache import never_cache, cache_control
from django.db.models import Q
from .forms import *
from .models import Contractor
import csv, json
from io import TextIOWrapper
# Create your views here.


#@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@login_required(login_url='/login/')
@never_cache

def contract(request):
    with connection.cursor() as cursor:
        cursor.execute("SELECT id, first_name, last_name, phone, email, badge, created_by, created_on FROM Contractors")
        contractors = cursor.fetchall()
        #if contractors:
            #print(contractors)

    contractors_data = []
    for contractor in contractors:
        contractor_data = {
            'id': contractor[0],
            'first_name': contractor[1],
            'last_name': contractor[2],
            'phone': contractor[3],
            'email': contractor[4],
            'badge': contractor[5],
            'created_by': contractor[6],
            'created_on': contractor[7],
        }
        contractors_data.append(contractor_data)
    return render(request, 'contractor.html', {'contractors': contractors_data})
    


@login_required(login_url='/login/')
@never_cache

def welcome(request):

    if request.method == 'POST':
        form = CommunicatonsForm(request.POST)
        if form.is_valid():
            """The issue was with the condition and 'submit' in request.POST in your welcome view. This condition was checking if the string 'submit' was present in the request.POST dictionary, which is not necessary for checking form validity and saving data.
            When a form is submitted, Django automatically populates request.POST with the form data. The is_valid() method of the form checks if the submitted data is valid based on the form's fields and validation rules.
            By removing and 'submit' in request.POST, the form is saved whenever it is valid, regardless of the submit button being clicked. This change allows the form to be saved correctly when submitted."""
            form.save()
            print(form.cleaned_data)
            request.session['comm-form-submitted'] = True
            return redirect('import_contractors')
        else:
            print("Form Invalid")
        
    else:
        form = CommunicatonsForm()
    return render(request, 'home_view.html', {'form': form})


 
@login_required(login_url='/login/')
@never_cache

def import_contractors(request):
    exists, mismatch = [], []
    if request.method == 'POST':
        csv_file = request.FILES.get('csv_file')

        if not csv_file or not csv_file.name.lower().endswith('.csv'):
            messages.error(request, 'Please upload a valid CSV file.')
            return render(request, 'import_contractors.html')

        with connection.cursor() as cursor:
            try:
                csv_data = TextIOWrapper(csv_file.file, encoding='utf-8')
                csv_reader = csv.reader(csv_data)
                next(csv_reader)  # Skip header row

                for row in csv_reader:
                    # Extract fields from CSV
                    first_name, last_name, phone, email, badge, created_by = row[:6]

                    # Check for existing contrasouctor in the database
                    cursor.execute(
                        "SELECT first_name, last_name, phone, email, badge, created_by FROM Contractors WHERE first_name = %s AND last_name = %s AND phone = %s AND email = %s AND badge = %s AND created_by = %s",
                        [first_name, last_name, phone, email, badge, created_by]
                    )
                    existing_contractor = cursor.fetchone()
                    print("Checking contractor:", first_name, last_name, phone, email, badge, created_by)
                    if existing_contractor:
                        # Append existing contractor to the list
                        exists.append(existing_contractor)
                        #print("Found:",existing_contractor)
                    else:
                        # Append mismatched contractor to the list
                        mismatch.append([first_name, last_name, phone, email, badge, created_by])

                messages.success(request, 'Contractors checked successfully.')
            except Exception as e:
                messages.error(request, f'An error occurred: {e}')
            
            request.session['exists'] = exists
            request.session['mismatch'] = mismatch
            return redirect('handle_contractors')
    
    return render(request, 'import_contractors.html')


@login_required(login_url='/login/')
@never_cache

def handle_contractors(request):

    #if request.session.get('comm-form-submitted'):
    exists_list = request.session.get('exists')
    mismatch_list = request.session.get('mismatch')
    
     
    return render(request, 'handle_contractors.html', {'existing_contractors': exists_list, 'mismatched_contractors': mismatch_list})


@login_required(login_url='/login/')
@never_cache

def review_contractors(request):
    review_set = set(tuple(item) for item in request.session.get('exists', []))
    filtered_contractors = None

    if request.method == 'POST':
        selected_contractors = request.POST.getlist('selected_contractors')
        if selected_contractors:
            for item in selected_contractors:
                contractor_data = tuple(item.split(','))
                review_set.add(contractor_data)
            
            # Convert the set back to a list for the session storage
            review_list = [list(contractor) for contractor in review_set]
            request.session['exists'] = review_list
        else:
            first_name = request.POST.get('first_name', '')
            last_name = request.POST.get('last_name', '')
            badge = request.POST.get('badge', '')
            phone = request.POST.get('phone', '')

            filters = Q()
            if first_name:
                filters &= Q(first_name__icontains=first_name)
            if last_name:
                filters &= Q(last_name__icontains=last_name)
            if badge:
                filters &= Q(badge__icontains=badge)
            if phone:
                filters &= Q(phone__icontains=phone)

            # Apply filters to existing contractors list
            if filters:
                filtered_contractors = Contractor.objects.filter(filters)

    review_list = [list(contractor) for contractor in review_set]
    return render(request, 'review_contractors.html', {
        'review_list': review_list,
        'filtered_contractors': filtered_contractors,
    })

def todo_list(request):
    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse('<script>window.close();</script>')  # Redirect to success page after saving
    else:
        form = TodoForm() 
    return render(request, 'todo.html', {'form': form})

def clogout(request):
    logout(request)
    response = redirect(reverse('login'))
    return response


"""exists, mismatch = [], []
    if request.method == 'POST':
        csv_file = request.FILES.get('csv_file')

        if not csv_file or not csv_file.name.lower().endswith('.csv'):
            messages.error(request, 'Please upload a valid CSV file.')
            return render(request, 'import_contractors.html')

        with connection.cursor() as cursor:
            try:
                csv_data = TextIOWrapper(csv_file.file, encoding='utf-8')
                csv_reader = csv.reader(csv_data)
                next(csv_reader)  # Skip header row
                for row in csv_reader:
                    #id = int(row[0])
                    first_name = row[0]
                    last_name = row[1]
                    phone = row[2]
                    email = row[3]
                    badge = row[4]
                    created_by = row[5]
                    #created_on = row[7]
                    #print(row)  # Print the row that is being checked
                    cursor.execute("SELECT * FROM Contractors WHERE first_name = %s AND last_name = %s AND phone = %s AND email = %s AND badge = %s AND created_by = %s",
                                   [first_name, last_name, phone, email, badge, created_by])
                    existing_contractor = cursor.fetchone()
                    if existing_contractor:
                        print("Contractor Found in DB:", existing_contractor)
                        existing_contractor = existing_contractor[0:6]
                        print(existing_contractor)
                        exists.append(existing_contractor)
                    else:
                        #print("Contractor not found in database:", row)
                        row = row[0:6]
                
                        mismatch.append(row)
                messages.success(request, 'Contractors checked successfully.')
            except Exception as e:
                messages.error(request, f'An error occurred: {e}')
        
        # Redirect to handle_contractors with exists and mismatch as arguments
        request.session['exists'] = exists
        request.session['mismatch'] = mismatch
        return redirect('handle_contractors')
    
    return render(request, 'import_contractors.html')
"""

home/templates/contractor.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h2>Contractors</h2>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Badge</th>
                <th>Created By</th>
                <th>Created On</th>
            </tr>
        </thead>
        <tbody>
            {% for contractor in contractors %}
            <tr>
                <td>{{ contractor.id }}</td>
                <td>{{ contractor.first_name }}</td>
                <td>{{ contractor.last_name }}</td>
                <td>{{ contractor.phone }}</td>
                <td>{{ contractor.email }}</td>
                <td>{{ contractor.badge }}</td>
                <td>{{ contractor.created_by }}</td>
                <td>{{ contractor.created_on }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

home/templates/handle_contractors.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h2>Imported Contractors</h2>
    <h3>Mismatched Contractors</h3>
    <h4>Select Contractors to Add to Conversation</h4>
    <form method="POST" action="{% url 'review_contractors' %}">
        {% csrf_token %}
    <table class="table">
        <thead>
            <tr>
          
                <th>First Name</th>
                <th>Last Name</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Badge</th>
                <th>Created By</th>
                <th>Selection</th>

            </tr>
        </thead>
        <tbody>
            {% for contractor in mismatched_contractors %}
            <tr style="color: red;">
                <td>{{ contractor.0 }}</td>
                <td>{{ contractor.1 }}</td>
                <td>{{ contractor.2 }}</td>
                <td>{{ contractor.3 }}</td>
                <td>{{ contractor.4 }}</td>
                <td>{{ contractor.5 }}</td>
                <td>{{ contractor.6 }}</td>
              
                <td><input type="checkbox" name="selected_contractors" value="{{ contractor|join:',' }}"></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <h3>Matched Contractors</h3>

    <table class="table">
        <thead>
            <tr>
    
                <th>First Name</th>
                <th>Last Name</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Badge</th>
                <th>Created By</th>
       
            </tr>
        </thead>
        <tbody>
            {% for contractor in existing_contractors %}
            <tr>
                <td>{{ contractor.0 }}</td>
                <td>{{ contractor.1 }}</td>
                <td>{{ contractor.2 }}</td>
                <td>{{ contractor.3 }}</td>
                <td>{{ contractor.4 }}</td>
                <td>{{ contractor.5 }}</td>
                <td>{{ contractor.6 }}</td>
        
            
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="text-center mt-3">
        <button type="submit" class="btn btn-primary">Add Selected Contractors</button>
    </div>
</form>
</div>
{% endblock %}

home/templates/home_view.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!---form starts here-->

<div class="container">
  <h2>Communications Form</h2>
  <form method="post" enctype="multipart/form-data" class="row g-3">
    {% csrf_token %}
    <div class="col-md-6">
      <div class="mb-3">
        <label for="id_comm_class" class="form-label">Comm Class:</label>
        {{ form.comm_class }}
      </div>
      <div class="mb-3">
        <label for="id_label" class="form-label">Label:</label>
        {{ form.label }}
      </000>
      <div class="mb-3">
        <label for="id_service_type" class="form-label">Service Type:</label>
        {{ form.service_type }}
      </div>
      <div class="mb-3">
        <label for="id_comm_type" class="form-label">Comm Type:</label>
        {{ form.comm_type }}
      </div>
      <div class="mb-3">
        <label for="id_message" class="form-label">Message:</label>
        {{ form.message }}
      </div>
      <div class="mb-3">
        <label for="id_created_by" class="form-label">Created By:</label>
        {{ form.created_by }}
      </div>
    </div>
    <div class="col-md-6">
      <div class="mb-3">
        <label for="id_created_on" class="form-label">Created On:</label>
        {{ form.created_on }}
      </div>
      <div class="mb-3">
        <label for="id_notes" class="form-label">Notes:</label>
        {{ form.notes }}
      </div>
      <div class="mb-3 form-check">
        <input type="checkbox" class="form-check-input" id="id_is_parent" name="is_parent">
        <label class="form-check-label" for="id_is_parent">Is Parent:</label>
      </div>
      <div class="mb-3">
        <label for="id_parent_id" class="form-label">Parent ID:</label>
        {{ form.parent_id }}
      </div>
      <div class="mb-3">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </form>
</div>

{% endblock %}

home/templates/import_contractors.html
{% extends "base.html" %}
{%load static%}



{%block content%}

 <!---form starts here-->

 <div class="container">
    <h2>Import Contractors</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="csv_file" class="form-label">Upload CSV File:</label>
            <input type="file" name="csv_file" accept=".csv" class="form-control" id="csv_file">
        </div>
        <button type="submit" class="btn btn-primary">Import</button>
    </form>
</div>
{%endblock%}

home/templates/review_contractors.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h2>Review</h2>
    <h3>Search to Add</h3>
    <form method="POST" class="my-4">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-3 mb-2">
                <input type="text" name="first_name" class="form-control" placeholder="First Name">
            </div>
            <div class="col-md-3 mb-2">
                <input type="text" name="last_name" class="form-control" placeholder="Last Name">
            </div>
            <div class="col-md-3 mb-2">
                <input type="text" name="badge" class="form-control" placeholder="Badge">
            </div>
            <div class="col-md-3 mb-2">
                <input type="text" name="phone" class="form-control" placeholder="Phone">
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </div>
    </form>
    {% if filtered_contractors %}
    <h3>Filtered Contractors</h3>
    <form method="POST" id="add-selected-form" class="my-4">
        {% csrf_token %}
        <table class="table">
            <thead>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Phone</th>
                    <th>Email</th>
                    <th>Badge</th>
                    <th>Created By</th>
                    <th>Created On</th>
                    <th>Selection</th>
                </tr>
            </thead>
            <tbody>
                {% for contractor in filtered_contractors %}
                <tr>
                    <td>{{ contractor.first_name }}</td>
                    <td>{{ contractor.last_name }}</td>
                    <td>{{ contractor.phone }}</td>
                    <td>{{ contractor.email }}</td>
                    <td>{{ contractor.badge }}</td>
                    <td>{{ contractor.created_by }}</td>
                    <td>{{ contractor.created_on }}</td>
                   <!--<td><input type="checkbox" name="search_select" value="{{ contractor|join:',' }}"></td>-->
                   <td>
                    <a href="#" class="selectContractor btn btn-small btn-primary">Select</a>
                </tr>
                {% endfor %}
            </tbody>
        </table>
      
    </form>
    {% endif %}
    
    <h3>Review Contractors for Comms</h3>
    <table class="table" id="tblFinal">
        <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Badge</th>
                <th>Created By</th>
            </tr>
        </thead>
        <tbody>
            {% for contractor in review_list %}
            <tr>
                <td>{{ contractor.0 }}</td>
                <td>{{ contractor.1 }}</td>
                <td>{{ contractor.2 }}</td>
                <td>{{ contractor.3 }}</td>
                <td>{{ contractor.4 }}</td>
                <td>{{ contractor.5 }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% block scripts %}

<script type="text/javascript"> alert("Hello");
    $(document).ready(function() {
        console.log("jQuery is ready!");
    
        $(".selectContractor").click(function(event){
            event.preventDefault();
            var tr = $(this).closest("tr").clone();
            $(tr).appendTo("#tblFinal");
            console.log("Row added to the final table.");
        });
    });
</script>
{% endblock %}
{% endblock %}

home/templates/success.html
{% extends "base.html" %}
{%load static%}



{%block content%}

 <!---form starts here-->

<head>
    <h1> Success </h1>
</head>
{%endblock%}

home/templates/todo.html
{% extends "base.html" %}
{% block content %}
<!-- Modal for Todo Form -->
<div class="modal fade" id="todoModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Todo Form</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="id_task" class="form-label">Task</label>
                        {{ form.task }}
                    </div>
                    <div class="mb-3">
                        <label for="id_status" class="form-label">Status</label>
                        {{ form.status }}
                    </div>
                    <div class="mb-3">
                        <label for="id_description" class="form-label">Description</label>
                        {{ form.description }}
                    </div>
                    <div class="mb-3">
                        <label for="id_assigned_to" class="form-label">Assigned To</label>
                        {{ form.assigned_to }}
                    </div>
                    <div class="mb-3">
                        <label for="id_created_by" class="form-label">Created By</label>
                        {{ form.created_by }}
                    </div>
                    <div class="mb-3">
                        <label for="id_added_on" class="form-label">Added On</label>
                        {{ form.added_on }}
                    </div>
                    <div class="mb-3">
                        <label for="id_comm_id" class="form-label">Comm ID</label>
                        {{ form.comm_id }}
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Button to open Todo Form modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#todoModal">
    <i class="bi bi-check2-square"></i> ToDo
</button>
{% endblock %}

{% block scripts %}
<!-- Bootstrap JavaScript -->
<script src="{% static 'js/bootstrap.bundle.js' %}" type="text/javascript"></script>
{% endblock %}